# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

outer_times_rcpp <- function(a, b) {
    .Call(`_MYHRcpp_outer_times_rcpp`, a, b)
}

outer_leq_rcpp_v1 <- function(a, b) {
    .Call(`_MYHRcpp_outer_leq_rcpp_v1`, a, b)
}

KDE_rcpp_kernel <- function(X, x, K, h) {
    .Call(`_MYHRcpp_KDE_rcpp_kernel`, X, x, K, h)
}

KDEcv_K2B_rcpp_o1 <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_K2B_rcpp_o1`, X, h)
}

KDEcv_K2B_rcpp_o2 <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_K2B_rcpp_o2`, X, h)
}

NW_K2B_rcpp_o1 <- function(X, Y, x, h) {
    .Call(`_MYHRcpp_NW_K2B_rcpp_o1`, X, Y, x, h)
}

NW_K2B_rcpp_o2 <- function(X, Y, x, h) {
    .Call(`_MYHRcpp_NW_K2B_rcpp_o2`, X, Y, x, h)
}

NW_K2B_rcpp_n1 <- function(X, Y, x, h) {
    .Call(`_MYHRcpp_NW_K2B_rcpp_n1`, X, Y, x, h)
}

NWD_K2B_rcpp <- function(X, Y, x, y, h) {
    .Call(`_MYHRcpp_NWD_K2B_rcpp`, X, Y, x, y, h)
}

NWD_K2B_rcpp_v1 <- function(X, Y, x, y, h) {
    .Call(`_MYHRcpp_NWD_K2B_rcpp_v1`, X, Y, x, y, h)
}

CVMNW_K2B_rcpp_n1 <- function(X, Y, h, p_Y) {
    .Call(`_MYHRcpp_CVMNW_K2B_rcpp_n1`, X, Y, h, p_Y)
}

CVDNWuniY_K2B_rcpp_n1 <- function(X, Y, h, y, p_y) {
    .Call(`_MYHRcpp_CVDNWuniY_K2B_rcpp_n1`, X, Y, h, y, p_y)
}

KME_rcpp_n1 <- function(t_stop, is_event, t_event) {
    .Call(`_MYHRcpp_KME_rcpp_n1`, t_stop, is_event, t_event)
}

KME_w_rcpp_n1 <- function(t_stop, is_event, t_event, w) {
    .Call(`_MYHRcpp_KME_w_rcpp_n1`, t_stop, is_event, t_event, w)
}

dG1_normal_rcpp <- function(X, Y, n1, alpha, beta, sigma, iter_max, stop_tol) {
    .Call(`_MYHRcpp_dG1_normal_rcpp`, X, Y, n1, alpha, beta, sigma, iter_max, stop_tol)
}

lpL_normal_rcpp <- function(X, Y, n1, alpha, beta, sigma, iter_max, stop_tol) {
    .Call(`_MYHRcpp_lpL_normal_rcpp`, X, Y, n1, alpha, beta, sigma, iter_max, stop_tol)
}

dG1alt_normal_rcpp <- function(X, Y, n1, alpha, beta, sigma, gamma, iter_max, stop_tol) {
    .Call(`_MYHRcpp_dG1alt_normal_rcpp`, X, Y, n1, alpha, beta, sigma, gamma, iter_max, stop_tol)
}

lpLalt_normal_rcpp <- function(X, Y, n1, alpha, beta, sigma, gamma, iter_max, stop_tol) {
    .Call(`_MYHRcpp_lpLalt_normal_rcpp`, X, Y, n1, alpha, beta, sigma, gamma, iter_max, stop_tol)
}

dG1_logistic_rcpp <- function(X, Y, n1, alpha, beta, iter_max, stop_tol) {
    .Call(`_MYHRcpp_dG1_logistic_rcpp`, X, Y, n1, alpha, beta, iter_max, stop_tol)
}

lpL_logistic_rcpp <- function(X, Y, n1, alpha, beta, iter_max, stop_tol) {
    .Call(`_MYHRcpp_lpL_logistic_rcpp`, X, Y, n1, alpha, beta, iter_max, stop_tol)
}

dG1alt_logistic_rcpp <- function(X, Y, n1, alpha, beta, gamma, iter_max, stop_tol) {
    .Call(`_MYHRcpp_dG1alt_logistic_rcpp`, X, Y, n1, alpha, beta, gamma, iter_max, stop_tol)
}

lpLalt_logistic_rcpp <- function(X, Y, n1, alpha, beta, gamma, iter_max, stop_tol) {
    .Call(`_MYHRcpp_lpLalt_logistic_rcpp`, X, Y, n1, alpha, beta, gamma, iter_max, stop_tol)
}

auxLS_Lagrange_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, LS_beta, y_pts, eta) {
    .Call(`_MYHRcpp_auxLS_Lagrange_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, LS_beta, y_pts, eta)
}

aux_Lagrange_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, y_pts, eta) {
    .Call(`_MYHRcpp_aux_Lagrange_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, y_pts, eta)
}

auxLS_Lagrange_EX_normal_rcpp <- function(X, alpha, beta, sigma, phi, LS_beta, eta) {
    .Call(`_MYHRcpp_auxLS_Lagrange_EX_normal_rcpp`, X, alpha, beta, sigma, phi, LS_beta, eta)
}

aux_Lagrange_EX_normal_rcpp <- function(X, alpha, beta, sigma, phi, eta) {
    .Call(`_MYHRcpp_aux_Lagrange_EX_normal_rcpp`, X, alpha, beta, sigma, phi, eta)
}

auxLS_Lagrange_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, LS_beta, index, eta) {
    .Call(`_MYHRcpp_auxLS_Lagrange_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, LS_beta, index, eta)
}

aux_Lagrange_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, index, eta) {
    .Call(`_MYHRcpp_aux_Lagrange_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, index, eta)
}

auxLS_Lagrange_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, LS_beta, eta) {
    .Call(`_MYHRcpp_auxLS_Lagrange_EY_normal_rcpp`, X, alpha, beta, sigma, phi, LS_beta, eta)
}

aux_Lagrange_EY_normal_rcpp <- function(X, alpha, beta, sigma, phi, eta) {
    .Call(`_MYHRcpp_aux_Lagrange_EY_normal_rcpp`, X, alpha, beta, sigma, phi, eta)
}

auxLS_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, LS_beta, y_pts) {
    .Call(`_MYHRcpp_auxLS_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, LS_beta, y_pts)
}

aux_EXsubY_normal_rcpp <- function(X, alpha, beta, sigma, phi, y_pts) {
    .Call(`_MYHRcpp_aux_EXsubY_normal_rcpp`, X, alpha, beta, sigma, phi, y_pts)
}

auxLS_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, LS_beta, index) {
    .Call(`_MYHRcpp_auxLS_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, LS_beta, index)
}

aux_EYsubX_normal_rcpp <- function(X, alpha, beta, sigma, phi, index) {
    .Call(`_MYHRcpp_aux_EYsubX_normal_rcpp`, X, alpha, beta, sigma, phi, index)
}

aux_EXsubgroupY_logistic_rcpp <- function(X, alpha, beta, phi) {
    .Call(`_MYHRcpp_aux_EXsubgroupY_logistic_rcpp`, X, alpha, beta, phi)
}

auxLS_EYsubgroupX_logistic_rcpp <- function(X, alpha, beta, phi, LS_beta, index) {
    .Call(`_MYHRcpp_auxLS_EYsubgroupX_logistic_rcpp`, X, alpha, beta, phi, LS_beta, index)
}

aux_EYsubgroupX_logistic_rcpp <- function(X, alpha, beta, phi, index) {
    .Call(`_MYHRcpp_aux_EYsubgroupX_logistic_rcpp`, X, alpha, beta, phi, index)
}

diff_lL_normal_rcpp <- function(X, Y, alpha, beta, sigma) {
    .Call(`_MYHRcpp_diff_lL_normal_rcpp`, X, Y, alpha, beta, sigma)
}

diff_lL_logistic_rcpp <- function(X, Y, alpha, beta) {
    .Call(`_MYHRcpp_diff_lL_logistic_rcpp`, X, Y, alpha, beta)
}

eXsq_rcpp <- function(data_X) {
    .Call(`_MYHRcpp_eXsq_rcpp`, data_X)
}

eXsq_w_rcpp <- function(data_X, weight) {
    .Call(`_MYHRcpp_eXsq_w_rcpp`, data_X, weight)
}

Xsq_lowtri_rcpp <- function(data_X) {
    .Call(`_MYHRcpp_Xsq_lowtri_rcpp`, data_X)
}

twoXYsym_lowtri_rcpp <- function(data_X, data_Y) {
    .Call(`_MYHRcpp_twoXYsym_lowtri_rcpp`, data_X, data_Y)
}

ctingP_rcpp <- function(Y, y) {
    .Call(`_MYHRcpp_ctingP_rcpp`, Y, y)
}

ctingP_uni_rcpp <- function(Y, y) {
    .Call(`_MYHRcpp_ctingP_uni_rcpp`, Y, y)
}

pinv_rcpp <- function(M_A) {
    .Call(`_MYHRcpp_pinv_rcpp`, M_A)
}

solve_rcpp <- function(M_A, M_B) {
    .Call(`_MYHRcpp_solve_rcpp`, M_A, M_B)
}

inv_sympd_rcpp <- function(M_S) {
    .Call(`_MYHRcpp_inv_sympd_rcpp`, M_S)
}

eigen_rcpp <- function(M_S) {
    .Call(`_MYHRcpp_eigen_rcpp`, M_S)
}

chol_rcpp <- function(M_S) {
    .Call(`_MYHRcpp_chol_rcpp`, M_S)
}

GroupSum_rcpp <- function(MM, id) {
    .Call(`_MYHRcpp_GroupSum_rcpp`, MM, id)
}

countAinB_rcpp <- function(A, B) {
    .Call(`_MYHRcpp_countAinB_rcpp`, A, B)
}

countAinB_W_rcpp <- function(A, B, W) {
    .Call(`_MYHRcpp_countAinB_W_rcpp`, A, B, W)
}

rankAinB_rcpp <- function(A, B) {
    .Call(`_MYHRcpp_rankAinB_rcpp`, A, B)
}

outer_minus_rcpp <- function(a, b) {
    .Call(`_MYHRcpp_outer_minus_rcpp`, a, b)
}

outer_plus_rcpp <- function(a, b) {
    .Call(`_MYHRcpp_outer_plus_rcpp`, a, b)
}

outer_leq_rcpp <- function(a, b) {
    .Call(`_MYHRcpp_outer_leq_rcpp`, a, b)
}

outer_geq_rcpp <- function(a, b) {
    .Call(`_MYHRcpp_outer_geq_rcpp`, a, b)
}

atRisk_integral_rcpp <- function(integrand, t_start, t_stop, t_event) {
    .Call(`_MYHRcpp_atRisk_integral_rcpp`, integrand, t_start, t_stop, t_event)
}

sum_atRisk_rcpp <- function(summand, t_start, t_stop, t_event) {
    .Call(`_MYHRcpp_sum_atRisk_rcpp`, summand, t_start, t_stop, t_event)
}

KDE_K2B_rcpp <- function(X, x, h) {
    .Call(`_MYHRcpp_KDE_K2B_rcpp`, X, x, h)
}

KDE_K2B_w_rcpp <- function(X, x, h, w) {
    .Call(`_MYHRcpp_KDE_K2B_w_rcpp`, X, x, h, w)
}

KDEcv_K2B_rcpp <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_K2B_rcpp`, X, h)
}

KDEcv_K2B_w_rcpp <- function(X, h, w) {
    .Call(`_MYHRcpp_KDEcv_K2B_w_rcpp`, X, h, w)
}

KDE_K4B_rcpp <- function(X, x, h) {
    .Call(`_MYHRcpp_KDE_K4B_rcpp`, X, x, h)
}

KDE_K4B_w_rcpp <- function(X, x, h, w) {
    .Call(`_MYHRcpp_KDE_K4B_w_rcpp`, X, x, h, w)
}

KDEcv_K4B_rcpp <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_K4B_rcpp`, X, h)
}

KDEcv_K4B_w_rcpp <- function(X, h, w) {
    .Call(`_MYHRcpp_KDEcv_K4B_w_rcpp`, X, h, w)
}

KDE_KG_rcpp <- function(X, x, h) {
    .Call(`_MYHRcpp_KDE_KG_rcpp`, X, x, h)
}

KDE_KG_w_rcpp <- function(X, x, h, w) {
    .Call(`_MYHRcpp_KDE_KG_w_rcpp`, X, x, h, w)
}

KDEcv_KG_rcpp <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_KG_rcpp`, X, h)
}

KDEcv_KG_w_rcpp <- function(X, h, w) {
    .Call(`_MYHRcpp_KDEcv_KG_w_rcpp`, X, h, w)
}

NW_K2B_rcpp <- function(X, Y, x, h) {
    .Call(`_MYHRcpp_NW_K2B_rcpp`, X, Y, x, h)
}

NW_K2B_w_rcpp <- function(X, Y, x, h, w) {
    .Call(`_MYHRcpp_NW_K2B_w_rcpp`, X, Y, x, h, w)
}

NWcv_K2B_rcpp <- function(X, Y, h) {
    .Call(`_MYHRcpp_NWcv_K2B_rcpp`, X, Y, h)
}

NWcv_K2B_w_rcpp <- function(X, Y, h, w) {
    .Call(`_MYHRcpp_NWcv_K2B_w_rcpp`, X, Y, h, w)
}

NW_K4B_rcpp <- function(X, Y, x, h) {
    .Call(`_MYHRcpp_NW_K4B_rcpp`, X, Y, x, h)
}

NW_K4B_w_rcpp <- function(X, Y, x, h, w) {
    .Call(`_MYHRcpp_NW_K4B_w_rcpp`, X, Y, x, h, w)
}

NWcv_K4B_rcpp <- function(X, Y, h) {
    .Call(`_MYHRcpp_NWcv_K4B_rcpp`, X, Y, h)
}

NWcv_K4B_w_rcpp <- function(X, Y, h, w) {
    .Call(`_MYHRcpp_NWcv_K4B_w_rcpp`, X, Y, h, w)
}

NW_KG_rcpp <- function(X, Y, x, h) {
    .Call(`_MYHRcpp_NW_KG_rcpp`, X, Y, x, h)
}

NW_KG_w_rcpp <- function(X, Y, x, h, w) {
    .Call(`_MYHRcpp_NW_KG_w_rcpp`, X, Y, x, h, w)
}

NWcv_KG_rcpp <- function(X, Y, h) {
    .Call(`_MYHRcpp_NWcv_KG_rcpp`, X, Y, h)
}

NWcv_KG_w_rcpp <- function(X, Y, h, w) {
    .Call(`_MYHRcpp_NWcv_KG_w_rcpp`, X, Y, h, w)
}

CVMNW_K2B_rcpp <- function(X, Y, h, p_Y) {
    .Call(`_MYHRcpp_CVMNW_K2B_rcpp`, X, Y, h, p_Y)
}

CVMNW_K2B_w_rcpp <- function(X, Y, h, p_Y, w) {
    .Call(`_MYHRcpp_CVMNW_K2B_w_rcpp`, X, Y, h, p_Y, w)
}

CVMNW_K4B_rcpp <- function(X, Y, h, p_Y) {
    .Call(`_MYHRcpp_CVMNW_K4B_rcpp`, X, Y, h, p_Y)
}

CVMNW_K4B_w_rcpp <- function(X, Y, h, p_Y, w) {
    .Call(`_MYHRcpp_CVMNW_K4B_w_rcpp`, X, Y, h, p_Y, w)
}

CVMNW_KG_rcpp <- function(X, Y, h, p_Y) {
    .Call(`_MYHRcpp_CVMNW_KG_rcpp`, X, Y, h, p_Y)
}

CVMNW_KG_w_rcpp <- function(X, Y, h, p_Y, w) {
    .Call(`_MYHRcpp_CVMNW_KG_w_rcpp`, X, Y, h, p_Y, w)
}

CVMNWdist_K4B_rcpp <- function(X, Y_CP, h, p_Y) {
    .Call(`_MYHRcpp_CVMNWdist_K4B_rcpp`, X, Y_CP, h, p_Y)
}

CVMNWdist_K4B_w_rcpp <- function(X, Y_CP, h, p_Y, w) {
    .Call(`_MYHRcpp_CVMNWdist_K4B_w_rcpp`, X, Y_CP, h, p_Y, w)
}

CVDNWuniY_K2B_rcpp <- function(X, Y, h, rank_y_in_Y, p_y) {
    .Call(`_MYHRcpp_CVDNWuniY_K2B_rcpp`, X, Y, h, rank_y_in_Y, p_y)
}

CVDNWuniY_K2B_w_rcpp <- function(X, Y, h, rank_y_in_Y, p_y, w) {
    .Call(`_MYHRcpp_CVDNWuniY_K2B_w_rcpp`, X, Y, h, rank_y_in_Y, p_y, w)
}

CVDNWuniY_K4B_rcpp <- function(X, Y, h, rank_y_in_Y, p_y) {
    .Call(`_MYHRcpp_CVDNWuniY_K4B_rcpp`, X, Y, h, rank_y_in_Y, p_y)
}

CVDNWuniY_K4B_w_rcpp <- function(X, Y, h, rank_y_in_Y, p_y, w) {
    .Call(`_MYHRcpp_CVDNWuniY_K4B_w_rcpp`, X, Y, h, rank_y_in_Y, p_y, w)
}

CVDNWuniY_KG_rcpp <- function(X, Y, h, rank_y_in_Y, p_y) {
    .Call(`_MYHRcpp_CVDNWuniY_KG_rcpp`, X, Y, h, rank_y_in_Y, p_y)
}

CVDNWuniY_KG_w_rcpp <- function(X, Y, h, rank_y_in_Y, p_y, w) {
    .Call(`_MYHRcpp_CVDNWuniY_KG_w_rcpp`, X, Y, h, rank_y_in_Y, p_y, w)
}

SSMNW_K2B_rcpp <- function(X, Y, h, p_Y) {
    .Call(`_MYHRcpp_SSMNW_K2B_rcpp`, X, Y, h, p_Y)
}

SSMNW_K2B_w_rcpp <- function(X, Y, h, p_Y, w) {
    .Call(`_MYHRcpp_SSMNW_K2B_w_rcpp`, X, Y, h, p_Y, w)
}

SSMNW_K4B_rcpp <- function(X, Y, h, p_Y) {
    .Call(`_MYHRcpp_SSMNW_K4B_rcpp`, X, Y, h, p_Y)
}

SSMNW_K4B_w_rcpp <- function(X, Y, h, p_Y, w) {
    .Call(`_MYHRcpp_SSMNW_K4B_w_rcpp`, X, Y, h, p_Y, w)
}

SSMNW_KG_rcpp <- function(X, Y, h, p_Y) {
    .Call(`_MYHRcpp_SSMNW_KG_rcpp`, X, Y, h, p_Y)
}

SSMNW_KG_w_rcpp <- function(X, Y, h, p_Y, w) {
    .Call(`_MYHRcpp_SSMNW_KG_w_rcpp`, X, Y, h, p_Y, w)
}

SSMNWdist_K4B_rcpp <- function(X, Y_CP, h, p_Y) {
    .Call(`_MYHRcpp_SSMNWdist_K4B_rcpp`, X, Y_CP, h, p_Y)
}

SSMNWdist_K4B_w_rcpp <- function(X, Y_CP, h, p_Y, w) {
    .Call(`_MYHRcpp_SSMNWdist_K4B_w_rcpp`, X, Y_CP, h, p_Y, w)
}

SSDNWuniY_K2B_rcpp <- function(X, Y, h, rank_y_in_Y, p_y) {
    .Call(`_MYHRcpp_SSDNWuniY_K2B_rcpp`, X, Y, h, rank_y_in_Y, p_y)
}

SSDNWuniY_K2B_w_rcpp <- function(X, Y, h, rank_y_in_Y, p_y, w) {
    .Call(`_MYHRcpp_SSDNWuniY_K2B_w_rcpp`, X, Y, h, rank_y_in_Y, p_y, w)
}

SSDNWuniY_K4B_rcpp <- function(X, Y, h, rank_y_in_Y, p_y) {
    .Call(`_MYHRcpp_SSDNWuniY_K4B_rcpp`, X, Y, h, rank_y_in_Y, p_y)
}

SSDNWuniY_K4B_w_rcpp <- function(X, Y, h, rank_y_in_Y, p_y, w) {
    .Call(`_MYHRcpp_SSDNWuniY_K4B_w_rcpp`, X, Y, h, rank_y_in_Y, p_y, w)
}

SSDNWuniY_KG_rcpp <- function(X, Y, h, rank_y_in_Y, p_y) {
    .Call(`_MYHRcpp_SSDNWuniY_KG_rcpp`, X, Y, h, rank_y_in_Y, p_y)
}

SSDNWuniY_KG_w_rcpp <- function(X, Y, h, rank_y_in_Y, p_y, w) {
    .Call(`_MYHRcpp_SSDNWuniY_KG_w_rcpp`, X, Y, h, rank_y_in_Y, p_y, w)
}

KME_rcpp <- function(t_stop, is_event, t_event) {
    .Call(`_MYHRcpp_KME_rcpp`, t_stop, is_event, t_event)
}

KME_w_rcpp <- function(t_stop, is_event, t_event, w) {
    .Call(`_MYHRcpp_KME_w_rcpp`, t_stop, is_event, t_event, w)
}

SKME_K2B_rcpp <- function(t_stop, is_event, t_event, X, x, h) {
    .Call(`_MYHRcpp_SKME_K2B_rcpp`, t_stop, is_event, t_event, X, x, h)
}

SKME_K2B_w_rcpp <- function(t_stop, is_event, t_event, X, x, h, w) {
    .Call(`_MYHRcpp_SKME_K2B_w_rcpp`, t_stop, is_event, t_event, X, x, h, w)
}

SKME_K4B_rcpp <- function(t_stop, is_event, t_event, X, x, h) {
    .Call(`_MYHRcpp_SKME_K4B_rcpp`, t_stop, is_event, t_event, X, x, h)
}

SKME_K4B_w_rcpp <- function(t_stop, is_event, t_event, X, x, h, w) {
    .Call(`_MYHRcpp_SKME_K4B_w_rcpp`, t_stop, is_event, t_event, X, x, h, w)
}

SKME_KG_rcpp <- function(t_stop, is_event, t_event, X, x, h) {
    .Call(`_MYHRcpp_SKME_KG_rcpp`, t_stop, is_event, t_event, X, x, h)
}

SKME_KG_w_rcpp <- function(t_stop, is_event, t_event, X, x, h, w) {
    .Call(`_MYHRcpp_SKME_KG_w_rcpp`, t_stop, is_event, t_event, X, x, h, w)
}

rcpp_hello <- function() {
    .Call(`_MYHRcpp_rcpp_hello`)
}

testfunction <- function(a, my_r_func) {
    .Call(`_MYHRcpp_testfunction`, a, my_r_func)
}

