# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eXsq_rcpp <- function(data_X) {
    .Call(`_MYHRcpp_eXsq_rcpp`, data_X)
}

eXsq_w_rcpp <- function(data_X, weight) {
    .Call(`_MYHRcpp_eXsq_w_rcpp`, data_X, weight)
}

Xsq_lowtri_rcpp <- function(data_X) {
    .Call(`_MYHRcpp_Xsq_lowtri_rcpp`, data_X)
}

twoXYsym_lowtri_rcpp <- function(data_X, data_Y) {
    .Call(`_MYHRcpp_twoXYsym_lowtri_rcpp`, data_X, data_Y)
}

pinv_rcpp <- function(M_A) {
    .Call(`_MYHRcpp_pinv_rcpp`, M_A)
}

solve_rcpp <- function(M_A, M_B) {
    .Call(`_MYHRcpp_solve_rcpp`, M_A, M_B)
}

inv_sympd_rcpp <- function(M_S) {
    .Call(`_MYHRcpp_inv_sympd_rcpp`, M_S)
}

eigen_rcpp <- function(M_S) {
    .Call(`_MYHRcpp_eigen_rcpp`, M_S)
}

GroupSum_rcpp <- function(MM, id) {
    .Call(`_MYHRcpp_GroupSum_rcpp`, MM, id)
}

countAinB_rcpp <- function(A, B) {
    .Call(`_MYHRcpp_countAinB_rcpp`, A, B)
}

countAinB_W_rcpp <- function(A, B, W) {
    .Call(`_MYHRcpp_countAinB_W_rcpp`, A, B, W)
}

rankAinB_rcpp <- function(A, B) {
    .Call(`_MYHRcpp_rankAinB_rcpp`, A, B)
}

atRisk_integral_rcpp <- function(integrand, t_start, t_stop, t_event) {
    .Call(`_MYHRcpp_atRisk_integral_rcpp`, integrand, t_start, t_stop, t_event)
}

sum_atRisk_rcpp <- function(summand, t_start, t_stop, t_event) {
    .Call(`_MYHRcpp_sum_atRisk_rcpp`, summand, t_start, t_stop, t_event)
}

KDE_KG_rcpp <- function(X, x, h) {
    .Call(`_MYHRcpp_KDE_KG_rcpp`, X, x, h)
}

KDE_KG_w_rcpp <- function(X, x, h, w) {
    .Call(`_MYHRcpp_KDE_KG_w_rcpp`, X, x, h, w)
}

KDEcv_KG_rcpp <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_KG_rcpp`, X, h)
}

KDEcv_KG_w_rcpp <- function(X, h, w) {
    .Call(`_MYHRcpp_KDEcv_KG_w_rcpp`, X, h, w)
}

KDE_K2B_rcpp <- function(X, x, h) {
    .Call(`_MYHRcpp_KDE_K2B_rcpp`, X, x, h)
}

KDE_K2B_w_rcpp <- function(X, x, h, w) {
    .Call(`_MYHRcpp_KDE_K2B_w_rcpp`, X, x, h, w)
}

KDEcv_K2B_rcpp <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_K2B_rcpp`, X, h)
}

KDEcv_K2B_w_rcpp <- function(X, h, w) {
    .Call(`_MYHRcpp_KDEcv_K2B_w_rcpp`, X, h, w)
}

KDE_K4B_rcpp <- function(X, x, h) {
    .Call(`_MYHRcpp_KDE_K4B_rcpp`, X, x, h)
}

KDE_K4B_w_rcpp <- function(X, x, h, w) {
    .Call(`_MYHRcpp_KDE_K4B_w_rcpp`, X, x, h, w)
}

KDEcv_K4B_rcpp <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_K4B_rcpp`, X, h)
}

KDEcv_K4B_w_rcpp <- function(X, h, w) {
    .Call(`_MYHRcpp_KDEcv_K4B_w_rcpp`, X, h, w)
}

NW_K2B_rcpp <- function(X, Y, x, h) {
    .Call(`_MYHRcpp_NW_K2B_rcpp`, X, Y, x, h)
}

NW_K2B_w_rcpp <- function(X, Y, x, h, w) {
    .Call(`_MYHRcpp_NW_K2B_w_rcpp`, X, Y, x, h, w)
}

NWcv_K2B_rcpp <- function(X, Y, h) {
    .Call(`_MYHRcpp_NWcv_K2B_rcpp`, X, Y, h)
}

NWcv_K2B_w_rcpp <- function(X, Y, h, w) {
    .Call(`_MYHRcpp_NWcv_K2B_w_rcpp`, X, Y, h, w)
}

NW_K4B_rcpp <- function(X, Y, x, h) {
    .Call(`_MYHRcpp_NW_K4B_rcpp`, X, Y, x, h)
}

NW_K4B_w_rcpp <- function(X, Y, x, h, w) {
    .Call(`_MYHRcpp_NW_K4B_w_rcpp`, X, Y, x, h, w)
}

NWcv_K4B_rcpp <- function(X, Y, h) {
    .Call(`_MYHRcpp_NWcv_K4B_rcpp`, X, Y, h)
}

NWcv_K4B_w_rcpp <- function(X, Y, h, w) {
    .Call(`_MYHRcpp_NWcv_K4B_w_rcpp`, X, Y, h, w)
}

rcpp_hello <- function() {
    .Call(`_MYHRcpp_rcpp_hello`)
}

KME_rcpp <- function(t_stop, is_event, t_event) {
    .Call(`_MYHRcpp_KME_rcpp`, t_stop, is_event, t_event)
}

KME_w_rcpp <- function(t_stop, is_event, t_event, w) {
    .Call(`_MYHRcpp_KME_w_rcpp`, t_stop, is_event, t_event, w)
}

SKME_K2B_rcpp <- function(t_stop, is_event, t_event, X, x, h) {
    .Call(`_MYHRcpp_SKME_K2B_rcpp`, t_stop, is_event, t_event, X, x, h)
}

SKME_K2B_w_rcpp <- function(t_stop, is_event, t_event, X, x, h, w) {
    .Call(`_MYHRcpp_SKME_K2B_w_rcpp`, t_stop, is_event, t_event, X, x, h, w)
}

SKME_K4B_rcpp <- function(t_stop, is_event, t_event, X, x, h) {
    .Call(`_MYHRcpp_SKME_K4B_rcpp`, t_stop, is_event, t_event, X, x, h)
}

SKME_K4B_w_rcpp <- function(t_stop, is_event, t_event, X, x, h, w) {
    .Call(`_MYHRcpp_SKME_K4B_w_rcpp`, t_stop, is_event, t_event, X, x, h, w)
}

testfunction <- function(a, my_r_func) {
    .Call(`_MYHRcpp_testfunction`, a, my_r_func)
}

KDE_rcpp_kernel <- function(X, x, K, h) {
    .Call(`_MYHRcpp_KDE_rcpp_kernel`, X, x, K, h)
}

KDE_K2B_rcpp_chatgpt <- function(X, x, h) {
    .Call(`_MYHRcpp_KDE_K2B_rcpp_chatgpt`, X, x, h)
}

KDEcv_K2B_rcpp_o1 <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_K2B_rcpp_o1`, X, h)
}

KDEcv_K2B_w_rcpp_o1 <- function(X, h, w) {
    .Call(`_MYHRcpp_KDEcv_K2B_w_rcpp_o1`, X, h, w)
}

KDE_K4B_rcpp_o1 <- function(X, x, h) {
    .Call(`_MYHRcpp_KDE_K4B_rcpp_o1`, X, x, h)
}

KDEcv_K4B_rcpp_o1 <- function(X, h) {
    .Call(`_MYHRcpp_KDEcv_K4B_rcpp_o1`, X, h)
}

NWF_K2B_rcpp <- function(X, Y, x, y, h) {
    .Call(`_MYHRcpp_NWF_K2B_rcpp`, X, Y, x, y, h)
}

NWcv_K2B_rcpp_o1 <- function(X, Y, h) {
    .Call(`_MYHRcpp_NWcv_K2B_rcpp_o1`, X, Y, h)
}

